server:
  port: 8080

spring:
  datasource:
    password: dima##skill**Box
    url: jdbc:mysql://localhost:3306/search_engine?serverTimezone=UTC&useSSL=false
    username: root
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
